"""
OhMyInfo — Interest topic routing and boosting module.

Converts user interest keywords into source-specific collection strategies
and provides score-boosting logic for articles matching those interests.

Usage::

    router = InterestRouter(["obsidian", "knowledge management"])
    strategy = router.get_strategy()
    # strategy.github_search_query  → "obsidian knowledge management"
    # strategy.reddit_search_queries → ["obsidian", "knowledge management"]
    # strategy.hn_filter_keywords   → ["obsidian", "knowledge management"]
    # strategy.arxiv_search_query   → "obsidian knowledge management"
    # strategy.devto_tags           → ["obsidian", "knowledge management"]

    boost = router.boost_score(article)  # 0-20
"""

from __future__ import annotations

from dataclasses import dataclass, field

from src.collectors import Article


# ---------------------------------------------------------------------------
# Topic strategy — collection hints per data source
# ---------------------------------------------------------------------------


@dataclass
class TopicStrategy:
    """How to search for a topic on each data source.

    Generated by :class:`InterestRouter` from a list of interest keywords.
    Empty strings/lists mean no special strategy for that source.

    Attributes:
        github_search_query:   Query string for the GitHub Search API
                               (e.g. ``"obsidian plugin"``).
        reddit_search_queries: List of subreddit search queries, one per
                               interest keyword.
        hn_filter_keywords:   Keywords to filter Hacker News stories by.
        arxiv_search_query:   Query string for the arXiv API search.
        devto_tags:           Tags to filter Dev.to articles by.
    """

    github_search_query: str = ""
    reddit_search_queries: list[str] = field(default_factory=list)
    hn_filter_keywords: list[str] = field(default_factory=list)
    arxiv_search_query: str = ""
    devto_tags: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Interest router
# ---------------------------------------------------------------------------


class InterestRouter:
    """Converts user interest keywords into topic-specific collection strategies.

    Takes a list of interest keywords (e.g., ``["obsidian", "knowledge management"]``)
    and generates optimised search queries for each data source.

    Also calculates score boosts for articles that match the interests.

    Args:
        interests: List of topic keywords from user preferences.
    """

    BOOST_TITLE_MATCH: float = 5.0
    BOOST_SUMMARY_MATCH: float = 3.0
    BOOST_TAG_MATCH: float = 3.0
    BOOST_MAX: float = 20.0

    def __init__(self, interests: list[str]) -> None:
        self._interests: list[str] = [kw.strip() for kw in interests if kw.strip()]

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_strategy(self) -> TopicStrategy:
        """Generate a collection strategy from interest keywords.

        Each non-empty interest keyword is mapped to every data source's
        search/filter format.

        Returns:
            A :class:`TopicStrategy` with per-source search hints.
        """
        if not self._interests:
            return TopicStrategy()

        return TopicStrategy(
            github_search_query=" ".join(self._interests),
            reddit_search_queries=list(self._interests),
            hn_filter_keywords=list(self._interests),
            arxiv_search_query=" ".join(self._interests),
            devto_tags=list(self._interests),
        )

    def boost_score(self, article: Article, base_score: float = 0.0) -> float:
        """Calculate an interest boost for an article (0-20 extra points).

        Checks if the article's title, summary, tags, or category match any
        registered interest keyword.

        * Article title matches an interest keyword → +5
        * Article summary matches an interest keyword → +3
        * Article tags contain an interest keyword → +3
        * Article category matches an interest keyword → +3

        Multiple matches can stack but the total boost is capped at +20.

        Args:
            article:    The article to evaluate.
            base_score: Reserved for future use (unused in current logic).

        Returns:
            A float between 0.0 and 20.0 representing the interest boost.
        """
        if not self._interests:
            return 0.0

        boost: float = 0.0
        title_lower = article.title.lower()
        summary_lower = article.summary.lower()
        category_lower = article.category.lower()
        tags_lower = [t.lower() for t in article.tags]

        for keyword in self._interests:
            kw_lower = keyword.lower()

            # Title match: +5
            if kw_lower in title_lower:
                boost += self.BOOST_TITLE_MATCH

            # Summary match: +3
            if kw_lower in summary_lower:
                boost += self.BOOST_SUMMARY_MATCH

            # Tag match: +3
            if any(kw_lower == t for t in tags_lower):
                boost += self.BOOST_TAG_MATCH

            # Category match: +3
            if kw_lower == category_lower:
                boost += self.BOOST_TAG_MATCH

        return min(boost, self.BOOST_MAX)


# ---------------------------------------------------------------------------
# Convenience
# ---------------------------------------------------------------------------


def boost_score(
    article: Article,
    interests: list[str],
    base_score: float = 0.0,
) -> float:
    """Convenience function — calculate interest boost for an article.

    Args:
        article:    The article to evaluate.
        interests:  List of interest keywords.
        base_score: Reserved for future use.

    Returns:
        Boost amount between 0.0 and 20.0.
    """
    return InterestRouter(interests).boost_score(article, base_score)
